# Generated by Django 5.0.6 on 2024-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_createduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvariant',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
